apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: prod
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector: 
              matchLabels:
               app: nginx
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/ece9016-cloud-computing/my-registry/app:v3
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config